---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9100'
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  type: ClusterIP
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100