---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: blackbox-config
  labels:
    app: blackbox
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
      http_post_2xx:
        prober: http
        http:
          method: POST
      tcp_connect:
        prober: tcp
      icmp:
        prober: icmp