---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: blackbox-deployment
  labels:
    app: blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
        - name: blackbox
          image: "prom/blackbox-exporter:latest"
          ports:
            - name: blackbox
              containerPort: 9115
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9115
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 9115
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: blackbox-volume
              mountPath: /etc/blackbox_exporter/
      volumes:
        - name: blackbox-volume
          configMap:
            name: blackbox-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534