---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.2.4
  name: kube-state-metrics
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: telemetry
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: kube-state-metrics