---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-prometeus
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi