---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/service: "prometheus"
    prometheus.io/port: "9090"
spec:
  selector:
    app: prometheus-server
  type: ClusterIP
  ports:
  - name: prometheus-web
    protocol: TCP
    port: 9090
    targetPort: 9090