apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: blackbox-config
  labels:
    app: blackbox
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
      http_post_2xx:
        prober: http
        http:
          method: POST
      tcp_connect:
        prober: tcp
      icmp:
        prober: icmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: blackbox-deployment
  labels:
    app: blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
        - name: blackbox
          image: "prom/blackbox-exporter:latest"
          ports:
            - name: blackbox
              containerPort: 9115
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9115
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 9115
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: blackbox-volume
              mountPath: /etc/blackbox_exporter/
      volumes:
        - name: blackbox-volume
          configMap:
            name: blackbox-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
---
kind: Service
apiVersion: v1
metadata:
  namespace: monitoring
  name: blackbox-service
  labels:
    app: blackbox
spec:
  type: ClusterIP
  selector:
    app: blackbox
  ports:
    - name: blackbox
      protocol: TCP
      port: 9115
      targetPort: 9115